name = "FaultDetectionTools"
uuid = "fbfc5fa0-0005-11ec-19bb-b3a492551a0b"
authors = ["Andreas Varga <varga.andreas@gmail.com>"]
version = "1.3.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DescriptorSystems = "a81e2ce2-54d1-11eb-2c75-db236b00f339"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixPencils = "48965c70-4690-11ea-1f13-43a2532b2fa8"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Combinatorics = "1.0"
DescriptorSystems = "1.4"
JLD2 = "0.4"
LinearAlgebra = "1"
MatrixEquations = "2.0"
MatrixPencils = "1.8"
Measurements = "2.11"
Polynomials = "2.0, 3, 4"
Optim = "1.7"
Random = "1"
Test = "1"
julia = "1.8"

[extras]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JLD2", "Measurements", "Optim", "Test"]
